### ISSUE TITLE
お？一ヶ月以上 Commit してないぞー？

### ISSUE THREAD

**Issue by toshiki670** [yuutarou22/CameMode#1]

**Comment by yuutarou22** [comment]
1ヶ月以上放置したことが原因で、ニフクラのデータ全て吹き飛びました。
リリース済みのアプリも飛びました( ◠‿◠ )

**Comment by toshiki670** [comment]
もう復旧無理な感じ？
ちなみにReadmeでタスク管理してるみたいだけど、Issueでタスク管理すると進捗分かりやすいよ〜

**Comment by yuutarou22** [comment]
Issue使ったことないから使ってみる！
